DROP DATABASE IF EXISTS Ejercicio6.sql;

CREATE DATABASE Ejercicio6.sql;

USE Ejercicio6.sql;

CREATE TABLE SOCIOS(
Nombre VARCHAR(20),
Direccion VARCHAR(30),
NumeroTelefono VARCHAR(15),
FechaInscripcion DATE,
N_Socio INT AUTO_INCREMENT,
PRIMARY KEY(N_socio)
);


CREATE TABLE LIBROS(

Titulo VARCHAR(30),
Autor VARCHAR(20),
Fecha_Editado DATE,
N_Libro BIGINT AUTO_INCREMENT,
PRIMARY KEY(N_Libro)
);

CREATE TABLE PRESTAMOS(
FECHA_RETIRO DATE, 
FECHA_ENTREGA DATE, 
N_SOCIO INT, 
N_LIBRO BIGINT, 
IDPrestamo BIGINT AUTO_INCREMENT,
PRIMARY KEY(IDPrestamo)
);

ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_SOCIO FOREIGN KEY (N_Socio) REFERENCES SOCIOS(N_Socio);
ALTER TABLE PRESTAMOS ADD CONSTRAINT FK_LIBROS FOREIGN KEY (_Libro) REFERENCES LIBROS(N_Libro);  
