DROP DATABASE IF EXISTS Ejercicio5;

CREATE DATABASE Ejercicio5;

USE Ejercicio5;

CREATE TABLE tab2 (col1 INT, col2 VARCHAR(25),
 PRIMARY KEY(col1, col2)); 

CREATE TABLE tab1 (col3 INT, col4 VARCHAR(25),
CONSTRAINT FK_tab3 FOREIGN KEY (col3) REFERENCES tab2(col1), CONSTRAINT FK_Tb4 FOREIGN KEY(col4) REFERENCES tab2(col2));

